interface tauri-log {
  //enum level {
  //  trace,
  //  debug,
  //  info,
  //  warn,
  //  error,
  //}

  func log(level: u32, message: string, location: string, file: option<string>, line: option<u32>)
}
