interface simple-lists {
  func simple-list1(l: list<u32>)
  func simple-list2() -> list<u32>
  // TODO: reenable this when smw implements this
  // simple-list3(a: list<u32>, b: list<u32>) -> tuple<list<u32>, list<u32>>
  func simple-list4(l: list<list<u32>>) -> list<list<u32>>
}
