interface simple_lists {
  func simple_list1(l: list<u32>)
  func simple_list2() -> list<u32>
  func simple_list3(a: list<u32>, b: list<u32>) -> tuple<list<u32>, list<u32>>
  func simple_list4(l: list<list<u32>>) -> list<list<u32>>
}
