interface integers {
  func a1(x: u8)
  func a2(x: s8)
  func a3(x: u16)
  func a4(x: s16)
  func a5(x: u32)
  func a6(x: s32)
  func a7(x: u64)
  func a8(x: s64)

  func a9(
    p1: u8,
    p2: s8,
    p3: u16,
    p4: s16,
    p5: u32,
    p6: s32,
    p7: u64,
    p8: s64,
  )


  func r1() -> u8
  func r2() -> s8
  func r3() -> u16
  func r4() -> s16
  func r5() -> u32
  func r6() -> s32
  func r7() -> u64
  func r8() -> s64

  func pair_ret() -> tuple<s64, u8>
}
